name: fsing_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dart_mappable: ^4.3.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.20.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  source_gen: ^1.5.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  build_runner: ^2.4.14
  freezed: ^2.5.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n
